### ISSUE TITLE
Migrate to cloudfoundry-samples org

### ISSUE THREAD

**Issue by afeld** [18F/cf-hello-worlds#22]
Just discovered https://github.com/cloudfoundry-samples, via https://github.com/18F/cf-hello-worlds/pull/21#issuecomment-204093500.

**Comment by afeld** [comment]
i.e. we should deprecate the ones that have community-maintained versions elsewhere, then create technology-specific repositories in that GitHub organization for the ones that don't exist yet.

**Comment by afeld** [comment]
FYI that I just got added to the org, for when we are ready to move stuff. New folks can get added by emailing cf-dev@lists.cloudfoundry.org, per https://cloudfoundry.slack.com/archives/cf-docs/p1474478566000077.

**Comment by pburkholder** [comment]
I think this repository has value to new users in that all of the samples are only "Hello World", and they all work. The cloudfoundry-samples has 70 repositories in various states of maintenance, many of which haven't been updated since 2013.

If we do migrate to cloudfoundry-samples I think it should be as a single repo `cloudgov-hello-worlds`, have tests to ensure deployability, and perhaps merge in https://github.com/cloudfoundry-samples/dotnet-core-hello-world. 

Meanwhile, I'd like to keep this running for cloud.gov.
